### --------------------------------------------------
### 1. Health Check
### --------------------------------------------------
GET http://127.0.0.1:5000/ping



### --------------------------------------------------
### 2. Create CART-WISE Coupon (Example 1)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "cart-wise",
  "details": {
    "threshold": 100,
    "discount": 10
  }
}



### --------------------------------------------------
### 3. Create CART-WISE Coupon (Example 2)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "cart-wise",
  "details": {
    "threshold": 500,
    "discount": 20
  }
}



### --------------------------------------------------
### 4. Create PRODUCT-WISE Coupon (Example 1)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "product-wise",
  "details": {
    "product_id": 1,
    "discount": 20
  }
}



### --------------------------------------------------
### 5. Create PRODUCT-WISE Coupon (Example 2)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "product-wise",
  "details": {
    "product_id": 2,
    "discount": 15
  }
}



### --------------------------------------------------
### 6. Create BxGy Coupon (Example 1)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "bxgy",
  "details": {
    "buy_products": [
      {
        "product_id": 1,
        "quantity": 2
      }
    ],
    "get_products": [
      {
        "product_id": 3,
        "quantity": 1
      }
    ],
    "repition_limit": 2
  }
}



### --------------------------------------------------
### 7. Create BxGy Coupon (Example 2)
### --------------------------------------------------
POST http://127.0.0.1:5000/coupons
Content-Type: application/json

{
  "type": "bxgy",
  "details": {
    "buy_products": [
      {
        "product_id": 2,
        "quantity": 3
      }
    ],
    "get_products": [
      {
        "product_id": 4,
        "quantity": 1
      }
    ],
    "repition_limit": 1
  }
}



### --------------------------------------------------
### 8. Get All Coupons
### --------------------------------------------------
GET http://127.0.0.1:5000/coupons



### --------------------------------------------------
### 9. Update Coupon
### --------------------------------------------------
PUT http://127.0.0.1:5000/coupons/1
Content-Type: application/json

{
  "type": "cart-wise",
  "details": {
    "threshold": 200,
    "discount": 15
  }
}



### --------------------------------------------------
### 10. Delete Coupon
### --------------------------------------------------
DELETE http://127.0.0.1:5000/coupons/2



### --------------------------------------------------
### 11. Check Applicable Coupons
### --------------------------------------------------
POST http://127.0.0.1:5000/applicable-coupons
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "product_id": 1,
        "quantity": 4,
        "price": 50
      },
      {
        "product_id": 3,
        "quantity": 2,
        "price": 25
      }
    ]
  }
}



### --------------------------------------------------
### 12. Apply Specific Coupon
### --------------------------------------------------
POST http://127.0.0.1:5000/apply-coupon/1
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "product_id": 1,
        "quantity": 4,
        "price": 50
      },
      {
        "product_id": 3,
        "quantity": 2,
        "price": 25
      }
    ]
  }
}